import math 

print("Es elipsoide o elipse meridiana")
print("1. Elipsoide")
print("2. Elpise ")
MenuUno= int(input("Escoja: "))
if MenuUno==1:
    print("Cual es el angulo inicial")
    print("1. Phi")
    print("2. Teta")
    print("3. w")
    MenuDos= int(input("Seleccione:  "))
    if MenuDos==1:
        print("Ingrese la Latitud:")
        graPhi = float(input("Grados: "))
        miPhi = float(input("Minutos: "))
        sePHI = float(input("Segundos: "))
        latPHI = graPhi+(miPhi/60)+(sePHI/3600)
        latPHI_rad=math.radians(latPHI)
        print("Ingrese la Longitud:")
        graLon = float(input("Grados: "))
        miLon = float(input("Minutos: "))
        seLon = float(input("Segundos: "))
        LonPHI = graLon+(miLon/60)+(seLon/3600)
        lonPHI_rad= math.radians(LonPHI)
        print("Ingrese el valor de a: ")
        a= float(input("Valor: "))
        print("Ingrese el valor de f^-1: ")
        f= float(input("Valor: "))
        print("Ingrese el valor de H: ")
        H= float(input("Valor: "))
        finv= 1/f
        e_cua = 2 * (finv) - (finv) ** 2
        w= math.sqrt(1 - (e_cua*math.sin(latPHI_rad)**2))
        N= a/w
        N_=N+H
        xgeod=N_*math.cos(latPHI_rad)*math.cos(lonPHI_rad)
        ygeod=(N_*math.cos(latPHI_rad)*(math.sin(lonPHI_rad)))
        zgeod=(N_*(1-e_cua)*(math.sin(latPHI_rad)))
       
        b=(a*math.sqrt(1-e_cua))
        tetaRadianes=math.atan((b/a)*math.tan(latPHI_rad))
        tetaGrados=math.degrees(tetaRadianes)
        xpar=a*math.cos(lonPHI_rad)

        print("==================================")
        print("COORDENADAS GEODESICAS")
        print(f"El valor de e es: {e_cua}")
        print(f"El valor de W es: {w}")
        print(f"El valor de N es: {N}")
        print(f"El valor de X es: {xgeod}")
        print(f"El valor de Y es: {ygeod}")
        print(f"El valor de Z es: {zgeod}")
        print("==================================")
        print("==================================")
        print("COORDENADAS PARAMETRICAS")
        print(f"El valor de teta es: {tetaGrados}")
        print(f"El valor de b es: {b}")
        print(f"El valor de a es: {a}")
        print(f"El valor de X es: {xgeod}")
        print(f"El valor de Y es: {ygeod}")
        print(f"El valor de Z es: {zgeod}")
        print("==================================")
        print("COORDENADAS GEOCENTRICAS")
        print(f"El valor de W es: {tetaGrados}")
        print(f"El valor de RGxyz es: {b}")
        print(f"El valor de a es: {a}")
        print(f"El valor de X es: {xgeod}")
        print(f"El valor de Y es: {ygeod}")
        print(f"El valor de Z es: {zgeod}")
        print("==================================")
if MenuUno==2:
    print("hola")